# Generated by Django 4.1.6 on 2023-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_userprofile_agent_oraganisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_oraganisor",
            field=models.BooleanField(default=True),
        ),
    ]
