# Generated by Django 4.1.6 on 2023-03-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_category_lead_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="oraganisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
        ),
    ]
