# Generated by Django 4.1.6 on 2023-03-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_category_oraganisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="oraganisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leads.userprofile"
            ),
        ),
    ]
