# Generated by Django 4.1.6 on 2023-03-26 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_alter_lead_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="data_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
