# Generated by Django 4.1.6 on 2023-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_lead_data_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
